### ISSUE TITLE
[Item 3] 싱글턴 인스턴스를 mocking 할 수 없는 이유

### ISSUE THREAD

**Issue by gmelon** [2023-java-study/book-study#10]
p.23 에서 `클래스를 싱글턴으로 만들면 이를 사용하는 클라이언트를 테스트하기가 어려워질 수 있다. (중략) 싱글턴 인스턴스를 가짜 (mock) 구현으로 대체할 수 없기 때문이다.` 라고 되어있는데 해당 클래스가 싱글턴인 것과 해당 클래스의 mock 객체를 만들 수 없는 것이 무슨 관계가 있는지 궁금합니다.

**Comment by Kim-AYoung** [comment]
mock 객체를 생성할 때 기본적으로 mocking할 클래스를 상속한 다음 메서드를 재정의하게되는데, 싱글턴 클래스의 생성자는 `private`이여서 상속이 불가능하므로 mocking이 불가능하다고 생각했습니다!

따라서 클래스의 mock 객체를 만들기위해서, 싱글턴이 아닌 클래스로 변경하여 해당 클래스의 인터페이스를 구현하는(만약, 해당 클래스의 인터페이스가 존재한다면..) 또다른 mock 클래스를 생성하여 DI한다고 하네요!

아래 블로그에 정리가 잘 되어있는 것 같습니다.
[https://velog.io/@backfox/싱글톤-패턴을-경계하는-사람들의-이야기](https://velog.io/@backfox/싱글톤-패턴을-경계하는-사람들의-이야기)
