### ISSUE TITLE
[item 32] 가변인수 배열의 노출

### ISSUE THREAD

**Issue by NuhGnod** [2023-java-study/book-study#104]
p.191
`내부로 감춰야 했을 이 배열을 그만 클라이언트에 노출하는 문제`
어떤 부분을 감춰야 했다고 말하는건가?

**Comment by ssstopeun** [comment]
저는 일반적으로도 이 배열이 노출된다고 이해했습니다.

메서드를 호출할때 `가변인수가 담긴 배열`이 자동 생성되고 이 배열의 값들로 메서드가 동작을 하기 때문에 일반적으로도 노출이 된다고 생각했습니다.

**Comment by gmelon** [comment]
```java
public void method(String... args) {
    String[] arr = args;
}
```

와 같이 가변인수로 선언된 인자를 (인자를 사용하는 메서드 입장에서) 배열로 사용할 수 있으므로 (즉, 메서드 입장에서 args가 배열임을 인지하게 되므로) `클라이언트에게 노출된다` 라는 표현을 썼다고 이해했습니다.
