### ISSUE TITLE
[item 32] 메서드가 반환하는 배열의 타입

### ISSUE THREAD

**Issue by ssstopeun** [2023-java-study/book-study#109]
p. 193
> 이 메서드가 반환하는 배열의 타입은 이 메서드에 인수를 넘기는 컴파일타임에 결정되는데, 그 시점에는 컴파일러에게 충분한 정보가 주어지지 않아 타입을 잘못 판단할 수 있다.

---
이 부분에서 컴파일러에게 줘야하는 충분한 정보 부분이 잘 이해가 되지 않습니다. 주어져야하는 충분한 정보는 무엇을 의미하는 건가요?

**Comment by NuhGnod** [comment]
#110 
어쩌다 보니 답변한 순서가 바뀌었지만, 110번 이슈로 답변드릴수 있을 것 같습니다!

정리하면, 해당 예시에 사용된 메서드(toArray, pickTwo)에서는 toArray에게 `T타입 인수`를 주고 있습니다.
`컴파일 타임`에 반환되는 배열의 타입이 결정된다고 하는데, `T타입 인수`를 주기 때문에 컴파일 시점에는 정확한 타입을 알 수 없고 `런타임`에 알 수 있게 됩니다.
따라서, 컴파일러는 컴파일 시점에는 정확한 타입을 모르므로 Object로 퉁치게 될겁니다.
결국, pickTwo메서드에서 Object배열을 반환하게 됩니다. 

그럼 p.194에 보면 `String[] attributes = pickTwo("좋은", "빠른", "저렴한")` 이 코드에서 Object배열이 String[]으로 다운캐스팅 되어 에러가 발생합니다.
