### ISSUE TITLE
[Item 3] 역직렬화 시 싱글턴이 깨지는 문제 해결 방법

### ISSUE THREAD

**Issue by gmelon** [2023-java-study/book-study#11]
본문에서 `readResolve()` 메서드를 구현하라고 되어있는 부분 보충 자료가 있어 첨부드립니당.

https://madplay.github.io/post/what-is-readresolve-method-and-writereplace-method

**Comment by ssstopeun** [comment]
싱글턴 클래스를 직렬화하는 경우는 어떤 경우인지, readResolve로 어떻게 방지되는지 이해가 잘 안돼요ㅠ

**Comment by Kim-AYoung** [comment]
인스턴스를 파일로 저장하기 위해 직렬화를 수행하고, 다시 읽어올  때 역직렬화를 수행하게되는데
역직렬화를 할 때 반드시 생성자를 통해 다시 한번 인스턴스를 만들기 때문에 직렬화에 사용한 인스턴스와는 전혀 다른 인스턴스가 된다고 하네요.
따라서 readResolve 메소드를 만들어두면 생성자를 사용하지 않고 해당 메서드를 통해 단 하나의 인스턴스만 반환하게 되므로 싱글톤이 직렬화시에도 보장되는것같습니다!
