### ISSUE TITLE
[Item 5] final 한정자와 멀티스레드 환경

### ISSUE THREAD

**Issue by gmelon** [2023-java-study/book-study#12]
p.29 에 `필드에서 final 한정자를 제거하고 (중략) 멀티스레드 환경에서는 쓸 수 없다` 라고 되어있는데 필드에서 final 키워드를 제거한 경우 해당 클래스를 멀티스레드 환경에서 사용할 수 없는 이유가 궁금합니다.

**Comment by ssstopeun** [comment]
멀티쓰레드환경에서 테스트하기 위해 간단히 코드를 짜보았습니다.

```java
import java.util.Dictionary;
import java.util.List;

public class SpellChecker {
    private static Lexicon dictionary = new KoreanDictionary();

    private SpellChecker(){}

    public static void changeDictionarytoEnglish(){
        dictionary = new EnglishDictionary();
    }

    public static Lexicon getDictionary(){
        return dictionary;
    }

    public static SpellChecker INSTANCE = new SpellChecker();

    public static boolean isValid(String word){
        return true;
    }
    public static List<String> suggestions(String typo){
        return null;
    }
}
```
우선 SpellChecker을 위와 같이 final을 제거해주고 영어 사전으로 교체하는 메서드를 추가할 수 있도록 해주고

```java
public class MultiThread extends Thread {
    MultiThread(){

    }
    public void run(){
        try{
            System.out.println(Thread.currentThread()+"dictionary : "+SpellChecker.getDictionary());
            SpellChecker.changeDictionarytoEnglish();
        }catch(Exception e){
            e.printStackTrace();
        }
    }
}
```
멀티쓰레드클래스에서는 쓰레드가 실행되었을 때, 현재 사전을 출력하고 사전이 바뀌도록 하였습니다.

```java
public class Main {
    public static void main(String[] args) throws Exception {
        Runnable task = new MultiThread();
        Thread subTread1 = new Thread(task);
        Thread subTread2 = new Thread(task);
        subTread1.start();
        subTread1.sleep(500);
        subTread2.start();

    }
}
```
그 후 main에서 subThread1이 시작되고 영어사전으로 바뀌고 난후 subThread2가 동작되었을때 멀티스레드 환경에서 사용하려면 subThread2가 한글사전부터 시작되어야 하는데 subThread1에서 영어사전으로 바뀐 dictonary가 작동하게 됩니다.

![image](https://user-images.githubusercontent.com/68415975/235438527-ac8ed16e-6981-42e2-86d2-2f450d7d2552.png)

위의 코드는 임시로 작성하여 MultiThread부분이 많이 어색하지만 Thread 별로 한글/영어/...사전을 동작하게 하는 코드를 생각해보면,

subThread1에서 changeDictionarytoEnglish()로 영어사전으로 바꾼 후 작업을 하고, subThread2는 한글사전으로 작업하고 싶은데 이 경우. subThread2는 subThread1에서 영어사전으로 바뀐 dictonary를 받아오게 되기때문에 원하는 동작이 이루어지지 않는 것 같습니다.
