### ISSUE TITLE
[Item 37] ordinal()을 사용했을때 ArrayIndexOutOfBoundsException이 발생하는 경우

### ISSUE THREAD

**Issue by ssstopeun** [2023-java-study/book-study#121]
p. 227
> 잘못된 값을 사용하면 잘못된 동작을 묵묵히 수행하거나 (운이 좋다면) ArrayIndexOutOf BoundsException을 던질 것이다.

여기서 예제에 나온 코드를 보면

```java
    Set<Plant>[] plantsByLifeCycle = (Set<Plant>[]) new Set[Plant.LifeCycle.values().length];

        for(int i=0;i<plantsByLifeCycle.length;i++){
            plantsByLifeCycle[i] = new HashSet<>();
        }
        Plant[] garden = new Plant[]{new Plant("장미", LifeCycle.ANNUAL), new Plant("국화",LifeCycle.ANNUAL),new Plant("해바라기",LifeCycle.PEPENNIAL)};

        for(Plant p : garden){
            plantsByLifeCycle[p.lifeCycle.ordinal()].add(p);
        }
        for(int i=0;i<plantsByLifeCycle.length;i++){
            System.out.printf("%s: %s%n", Plant.LifeCycle.values()[i], plantsByLifeCycle[i]);
        }
```

여기서 `plantsByLifeCycle`을 생성할 때 `plantsLifeCycle.values().length`로 생성하고 그렇게 되면 `p.lifeCycle.ordinal()`을 했을 때 범위 내에서만 인덱스가 생겨 문제가 없다고 생각했는데 책에 나온 것 처럼 `ArrayIndexOutOfBoundesException`이 나오는 경우가 어떤게 있을까요...?

**Comment by NuhGnod** [comment]
이 책의 예시대로만 사용하면 문제가 생길 것 같지는 않습니다.

예시로, EnumMap의 put메소드를 보면,
```java
public V put(K key, V value) {
        typeCheck(key);

        int index = key.ordinal();
        Object oldValue = vals[index];
        vals[index] = maskNull(value);
        if (oldValue == null)
            size++;
        return unmaskNull(oldValue);
    }
```
내부적으로 ordinal() 를 사용하여 index를 계산하고 있습니다. 저는 코드 37-1 에서 보여준 형태도 결국 이런 형태라고 생각합니다.
책에서 말한 부분은 `가장 심각한 문제 정확한 정숫값 사용한다 것을 여러분이 직접 보증해야 한다는 점이다.` 에서 알 수 있듯이 결국, 보증하기 힘든 문제라고 생각했습니다.

예시로, Enum은 oridinal()의 사용을 내부로 숨겨놓았습니다. 그래서 사용자들이 올바른 index를 사용하게 될 것임이 보장되었다고 생각합니다. 하지만, 코드 37-1 에서는 사용자들이 다음처럼 사용할 수 도 있습니다.
```java
// 잘못된 사용 1
    for(Plant p : garden){
            plantsByLifeCycle[0].add(p);
    }

// 잘못된 사용 2
    Plant.LifeCycle lc = plantsByLifeCycle[0];
    if(lc == Plant.LifeCycle.PERENNIAL)
```
이런식으로 사용자가 직접 index를 설정하여 조작하는 일을 막을 수 없게 됩니다.

그래서 운좋게 충분히 ArrayIndexOutOfBoundsException 이 발생할 수도 있고, 제가 들은 예시 처럼 잘못된 동작을 계속 수행해나가 게 될겁니다.
