### ISSUE TITLE
[item41] Set을 마커 인터페이스로 보는 경우

### ISSUE THREAD

**Issue by NuhGnod** [2023-java-study/book-study#126]
p.250

Set인터페이스를 마커 인터페이스로 볼 수 도 있다고 하는데, 저는 좀 받아들이기가 힘드네요..
우선 `마커 인터페이스`의 정의릘 p.249에서 `아무 메소드도 담고 있지 않고, 단지 자신을 구현하는 클래스가 특정 속성을 가짐을 표시해주는 인터페이스를 마커 인터페이스`라 한다. 라고 했습니다.

뭐, 마커 인터페이스의 기준을, `자신을 구현하는 클래스가 특정 속성을 가짐`에 비중을 두어 생각한다고 해도,
어떤의미에서 Set을 마커인터페이스라 볼 수 있는지에 대한 의문점이 듭니다.

**Comment by ssstopeun** [comment]
Set을 보면 Collection의 메서드들은 그대로 가져오는데 `add(E e)를 할때 중복되는 값은 추가하지 말아라`와 같은 규약만 재정의되어 있습니다. 이 규약을 지킬 수 있게 메서드가 수정된 것은 없었어요. Set을 구현하는 HashSet과 같은 클래스들에서 Set에 명시된 규약에 맞게 재정의 하는 것 같습니다. 
책에서 `Set이 제약이 있는 마커 인터페이스로 볼수있다`고 말하고 있는데 Set에 명시된 규약들을 이 제약이라고 이해했습니다.

동의하지 않는 사람도 있다는 걸 보니 완전 마커 인터페이스라고 할 수 는 없는 것 같고 p. 250 두번째 문단에
> 하지만 특정 인터페이스의 하위 타입에만 적용할 수 있으며, 아무 규약에도 손대지 않은 마커 인터페이스는 충분히 있음직하다.
고 적혀있는 걸 보고 Set에서 규약까지 재정의하지 않은 인터페이스를 완전한 마커 인터페이스라고 생각했습니다.

뭔가 반대로 말하면 Set은 마커인터페이스처럼 쓰고 있지만 규약을 재정의했기에 완전한 마커인터페이스라고는 할 수 없다. 는 느낌으로요!

**Comment by ssstopeun** [comment]
Set에 이부분은 메서드를 재정의하긴 했네요...
```java
@Override
    default Spliterator<E> spliterator() {
        return Spliterators.spliterator(this, Spliterator.DISTINCT);
    }
```
