### ISSUE TITLE
[Item 5] 하나 이상의 자원에 의존하는 클래스를 싱글턴과 정적 유틸리티 클래스로 만들면 안 되는 이유

### ISSUE THREAD

**Issue by gmelon** [2023-java-study/book-study#13]
p.30 **핵심 정리** 부분에 `클래스가 내부적으로 하나 이상의 자원에 의존하고, 그 자원이 클래스 동작에 영향을 준다면 싱글턴과 정적 유틸리티 클래스는 사용하지 않는 것이 좋다` 라고 되어있는데 이게 저는 단순히 정적 유틸리티 클래스나 싱글턴의 경우 생성자가 private 이므로 생성자를 통해 자원을 주입할 수 없기 때문에 사용하지 않는게 좋다고 생각했는데 혹시 읽으시면서 생각하신 다른 이유가 있다면 공유 부탁드립니다!

**Comment by ssstopeun** [comment]
저도 비슷하게 생각했습니다ㅜ 싱글톤 패턴이 인스턴스가 오직 1개일 경우에 사용하고 이를 안전하게 보증하기위해 private를 사용하잖아요. 그런데 하나 이상의 자원에 의존할때는 private 생성자로 이를 보증하게 될 필요가 없을 뿐더러 싱글톤이나 정적 유틸리티로 작성하였을때 유연하게 이 여러 자원들을 사용할 수 없기 때문이라고 생각했습니다.
