### ISSUE TITLE
[Item 3] 스레드별로 다른 인스턴스를 넘겨주게 하는 것

### ISSUE THREAD

**Issue by ssstopeun** [2023-java-study/book-study#15]
p. 24 정적 팩터리 방식의 첫번째 장점에서 `유일한 인스턴스를 반환하던 팩터리 메서드가 호출하는 스레드별로 다른 인스턴스를 넘겨주게 할 수 있다.` 고 되있는데 어떻게 되는 건가요? 코드 3-1 처럼 public static final 방식으로 작성하면 왜 안되나요

**Comment by Kim-AYoung** [comment]
코드 3-1에서는 INSTANCE라는 상속 변수를 통해서 인스턴스를 얻고 있는데 만약 이 클래스를 싱글턴이 아닌 클래스로 추후에 변경하게된다면 기존에 사용하던  INSTANCE라는 변수를 더이상 사용하지못하고 생성자를 통해 새로운 인스턴스를 얻는 방법으로 변경되어야 합니다. 
즉, 싱글턴이 아닌 클래스로 변경되어야할 때 인스턴스를 얻는 인터페이스가 바뀌게 되는 부분이 코드 3-1의 단점이라고 보았습니다. 3-2로 변경이되면 API를 바꾸지 않고도 싱글턴이 아닌 클래스로 변경할 수 있다고 생각했습니다!

`유일한 인스턴스를 반환하던 팩터리 메서드가 호출하는 스레드별로 다른 인스턴스를 넘겨주게 할 수 있다.`는 아래 코드처럼 싱글턴이 아닌 클래스로 변경하게 되면 다른 인스턴스를 매번 넘겨주므로 각기 다른 스레드가 다른 인스턴스를 사용할 수 있다 즉, 싱글턴이 아닌 클래스의 특징..? 중 하나로 생각했습니다!
```java
class Elvis {
    private static final Elvis INSTANCE = new Elvis();
    private Elvis() {}
    public static Elvis getInstance() {return new Elvis();}
    
    public void leaveTheBuilding() {}
}
```
