### ISSUE TITLE
[Item 4] 인스턴스화되는 것을 막는 이유

### ISSUE THREAD

**Issue by ssstopeun** [2023-java-study/book-study#16]
아이템 4에서 말하는 인스턴스화를 막으려고 하는 이유는 어떤게 있을까요?

**Comment by gmelon** [comment]
책에서 말하는 내용으로 보면 `Arrays`나 `Collections` 처럼 특정 인터페이스에 대한 구현체를 만들어주고 편의 메서드를 제공하는 클래스들은 굳이 인스턴스화 할 필요도 없고, 한다고 해서 할 수 있는 것도 없으므로 인스턴스화를 막는 예시가 될 수 있을 것 같습니다.
