### ISSUE TITLE
[Item 2] 버그를 심는 코드와 이 때문에 문제를 일으키는 코드가 멀리 떨어져 있는 경우

### ISSUE THREAD

**Issue by gmelon** [2023-java-study/book-study#2]
p.16 에서 `버그를 심은 코드와 그 버그 때문에 런타임에 문제를 겪는 코드가 물리적으로 멀리 떨어져 있을 것으로 디버깅도 만만치 않다` 라는 문장이 어떤 의미일까요?

저는 `setter를 호출하는 코드 (버그를 심은 코드)와 문제를 겪는 코드 (setter로 생성한 클래스의 다른 메서드)를 호출하는 클라이언트의 코드 간 간격이 멀다` 라고 이해했는데 어떻게 생각하시나용

**Comment by ssstopeun** [comment]
setter로 생성한 클래스의 다른 메서드라는게 p.16에서의 예시에서 setter를 통해 완전히 초기화 된 cocaCola 객체를 사용하는 쪽을 말하는 걸까요? 맞다면 저도 이렇게 생각했습니당

버그를 심은 코드 : setServingSize를 비롯한 setter들을 호출해 cocaCola 객체를 초기화하는 부분

버그 때문에 런타임에 문제를 겪는 코드 : 버그로 인해 불완전한 cocaCola 객체를 넘겨받아 구동되는 코드

로 이해했고 이 둘의 코드가 다른 클래스나 패키지일 수 있기 때문에 물리적으로 떨어져있다고 한 것 같아요.
