### ISSUE TITLE
이슈

### ISSUE THREAD

**Issue by NuhGnod** [2023-java-study/book-study#204]
pk, commen id, user id enabled
1 1 1 T
2 1 1 T
3 1 1 T
4 1 1 T

**Comment by NuhGnod** [comment]
1 1 1 F
2 1 1 T
3 1 1 T
4 1 1 T

**Comment by gmelon** [comment]
<img width="503" alt="image" src="https://github.com/2023-java-study/book-study/assets/33623106/7a257365-9c57-4d93-90cc-8ce862b8c57e">


<img width="452" alt="image" src="https://github.com/2023-java-study/book-study/assets/33623106/1670b0db-cd66-414d-a518-f0e3cad981a5">

**Comment by NuhGnod** [comment]
User ( 1 )  - Post ( N ) : 1 대 다 연관관계 
user 엔티티에서
@OneToMany로 post를 들고있다.
![image](https://github.com/2023-java-study/book-study/assets/37896242/b5807410-70fa-42eb-962d-1265554216bb)

---

이때 user 엔티티 전체 조회 쿼리 `select * from user` 상황)

## 수정 전 조회 결과

### post 데이터들을 보면 post title 값이  `ZZZZZZZ` 다음에 `Sampl22e` 인것을 볼 수 있음.

![image](https://github.com/2023-java-study/book-study/assets/37896242/385456be-a6c0-4085-97d2-51883e3dacfe)

## 수정 후 조회 결과 (  ZZZZZZ 값을 abcd 로 변경 )

### 순서가 바뀜.
![image](https://github.com/2023-java-study/book-study/assets/37896242/89b1e871-7b5c-4505-8886-4480e01348bb)

**Comment by NuhGnod** [comment]
```        List<User> all = userRepository.findAll();
        User u1 = all.get(0);
        System.out.println(u1.getPosts());
        u1.getPosts().forEach(
                p -> System.out.println(p.getPostTitle())
        );
```
이런 코드로 user의 posts 리스트에 데이터가 쌓이는 순서가 바뀐건가 확인해보았는데 List에는 순서가 유지됩니다.

그럼 실제로 프론트로 반환된 posts 데이터의 순서가 바뀌게 된것은
Jackson이 엔티티를 직렬화 시킬때  순서가 바뀌는것으로 예상되네요
