### ISSUE TITLE
[Item 7] WeakHashMap을 사용하는 예외적인 상황

### ISSUE THREAD

**Issue by NuhGnod** [2023-java-study/book-study#24]
p. 38에서 `캐시 역시 메모리 누수를 일으키는 주범이다.` 문단입니다.
해당 문단에서 `운 좋게 캐시 외부에서 키(key)를 참조하는 동안만 엔트리가 살아 있는 캐시가 필요한 상황이라면 WeakHashMap을 사용해 캐시를  만들자.` 라는 글에서 이 예외적인 상황이 뜻하는 의미가 딱 상상되지 않네요.

이 글에서 말하는  WeakHashMap을 사용하게 될 만한 상황이 무엇이 있을 지 궁금합니다.
또한, 일반적인 상황에서는 다음 문단에 나오는 LinkedHashMap 을 사용하여 캐시로 사용하면 되는 것 이라고 이해할 수 있을까요??

**Comment by gmelon** [comment]
말씀해주신 `운 좋게 캐시 외부에서 키를 참조하는 동안만 엔트리가 살아 있는 캐시가 필요한` 이란 문장은
제가 이해한 바로는 요구사항이 map에 (key, value) 를 넣는데 이때 사용한 **key에 대한 참조를 클라이언트에서 가지고 있는 동안에만 해당 entry가 유지되면 되는 캐시**인 경우를 말하는 것 같습니다.

보통은 key에 대한 참조가 당장 사라져도 다른 곳에서 가져와 캐시에 접근하게 될테니 이러한 상황이 운 좋은 상황이라고 표현한 것 같아요!

그래서 일반적으로는 시간이 지날 수록 엔트리의 가치를 떨어뜨리는 LinkedHashMap을 사용하게 된다고도 언급한 것 같습니다.

WeakHashMap에 대한 설명은 아래 issue에 정리해뒀으니 참고하시면 좋을 것 같아용
https://github.com/2023-java-study/book-study/issues/20
