### ISSUE TITLE
[Item 10] StackOverflowError가 어떻게 일어나나요?

### ISSUE THREAD

**Issue by ssstopeun** [2023-java-study/book-study#27]
p. 58, 4 ~ 7번째 줄이 잘 이해가 안되는데 무한재귀에 빠져 StackOverflowError가 어떻게 일어나게 되나요?

**Comment by gmelon** [comment]
==
p.60 `아무런 값을 갖지 않는 인스턴스화 불가능한 추상클래스가 상위 클래스라면 문제가 발생하지 않는다`
-> 얘도 고려하여 같이 예시 코드 작성하기
==

**Comment by gmelon** [comment]
예를 들어 Point 를 상속받는 두 클래스 ColorPoint와 SmellPoint의 equals()가 아래와 같다고 하면,
```java
```
