### ISSUE TITLE
[Item 11] hashcode 계산에 홀수를 사용하는 이유

### ISSUE THREAD

**Issue by gmelon** [2023-java-study/book-study#36]
p.70에 `만약 이 숫자가 짝수이고 오버플로우가 발생한다면 정보를 잃게 된다. 2를 곱하는 것은 시프트 연산과 같은 결과를 내기 때문이다` 라고 되어있습니다. 책에서는 이러한 이유로 hashcode 계산에 홀수를 사용한다고 하는데, 홀수를 사용해도 결국 계속해서 밀리고 오버플로우가 발생하면 정보를 잃는 것은 마찬가지 아닌가요..??

이 부분이 잘 이해되지 않아 혹시 어떻게 이해하셨는지 궁금합니다!!

**Comment by NuhGnod** [comment]
저도 간단히 책에서 나온 방법으로 hashCode를 구현하여 계산해봤었는데 31을 곱해도 오버플로우는 당연히 발생하더라구요.
그래서 찾아봤는데 `31 33 37 39 41 등의 숫자가 충돌이 적게 일어나는 수` 라는 얘기가 있더라구요! 그리고 31과 33은 시프트 연산후 -1 또는 +1로 빠르게 계산 할 수 있다는 점을 보아 31을 주로 사용한다는 것이 아닌가 싶습니다.
참고글 링크달아드릴게요
https://stackoverflow.com/questions/299304/why-does-javas-hashcode-in-string-use-31-as-a-multiplier

**Comment by ssstopeun** [comment]
JVM 에서 31 * i 을 (i << 5) - i 로 계산을 한다고 합니다. 그래서 짝수를 곱했을 때는 시프트 연산으로 오른쪽 값이 0으로 계속 채워지게 되는데 홀수를 곱하면 overflow가 났을때 오른쪽 값들이 0이 아닌 다른 값으로 채워질 수 있어서 해시충돌이 일어날 가능성이 낮아집니다. 홀수를 사용해야 오버플로우가 발생해도 hashCode값의 충돌이 적은 것 같습니다.

그래서 짝수를 사용하게 되면 overflow가 났을때 모든 값이 0으로 채워지게 되고 이렇게 되면 객체들의 hashCode값이 다 같아지니 각각의 객체들의 hashCode에 대한 명확한 정보가 없어진다는 의미로 이해했습니다.
