### ISSUE TITLE
[Item 11] 필드를 지연 초기화할 때 클래스를 thread-safe 하게 구현해야 하는 이유

### ISSUE THREAD

**Issue by gmelon** [2023-java-study/book-study#37]
p.71에 `필드를 지연 초기화하려면 그 클래스를 쓰레드 안전하게 만들도록 신경써야 한다` 라고 되어있습니다.

인스턴스 필드인 `hashcode`를 지연 초기화할 때 클래스가 `쓰레드 안전`해야 하는 이유가 궁금합니다.

**Comment by ssstopeun** [comment]
아이템 83에서 한다고 해서 그냥 넘어갔던 부분인데 해당 아이템을 가보니 `지연초기화하는 필드를 둘 이상의 스레드가 공유한다면 어떤 형태로든 반드시 동기화해야 한다. 그렇지 않으면 심각한 버그로 이어질 것이다.(아이템 78)` 이라고 되있었고 아이템 78에서는 `여러 스레드가 가변 데이터를 공유한다면 그 데이터를 일고 쓰는 동작은 반드시 동기화 해야한다.` 고 되있었어요. 해당 아이템을 공부해봐야 자세히 알겠지만 코드 11-4 에서 `private int hashCode`가 멀티스레드환경이라면 공유되고 있는 데이터고 그렇다면 앞선 아이템에서 말한 것과 같은 문제를 발생시키지 않기 위해 쓰레드 안전해야 한다고 한 것 아닐까요..?
