### ISSUE TITLE
[Item 12] 추상클래스에서의 toString 재정의

### ISSUE THREAD

**Issue by gmelon** [2023-java-study/book-study#39]
p.75 ~ 76에 `하위 클래스들이 공유해야 할 문자열 표현이 있는 추상 클래스라면 toString을 재정의해줘야 한다. 예컨데 대다수의 컬렉션 구현체는 추상 컬렉션 클래스들의 toString 메서드를 상속해 쓴다` 라고 되어있습니다.

이 부분을 읽고 몇 가지 궁금증이 생겼는데, 
1. 자바의 HashMap, HashSet 등 구체 컬렉션 클래스는 상위 추상 클래스인 AbstractMap 등의 toString을 상속받아서 어떤 식으로 변형해 사용하는지 궁금합니다
2. `하위 클래스들이 공유해야 할 문자열 표현이 있는` 이라는 문장의 의미가 `추상 클래스가 특정 인스턴스 필드를 갖고, 하위 구체 클래스에서 해당 필드를 핵심 필드로 사용하는 경우`를 의미한다고 이해했는데 제가 잘 이해한 건지 궁금합니다

**Comment by NuhGnod** [comment]
1.
HashMap의 경우 AbstractMap을 상속받고 있습니다. 그리고 toString() 메소드를 재정의하지 않고 `AbstractMap의 toString() 메소드를 그대로 쓰고있습니다`. 해당 HashMap클래스를 보면 toString()메소드가 없는 것을 확인 할 수 있습니다.
AbstractMap의 toString()메소드는 다음처럼 구현되었습니다.
```java
public String toString() {
        Iterator<Entry<K,V>> i = entrySet().iterator();
        if (! i.hasNext())
            return "{}";

        StringBuilder sb = new StringBuilder();
        sb.append('{');
        for (;;) {
            Entry<K,V> e = i.next();
            K key = e.getKey();
            V value = e.getValue();
            sb.append(key   == this ? "(this Map)" : key);
            sb.append('=');
            sb.append(value == this ? "(this Map)" : value);
            if (! i.hasNext())
                return sb.append('}').toString();
            sb.append(',').append(' ');
        }
    }
```
HashSet은 AbstractSet을 상속받고있고, AbstractSet은 AbstractCollection 을 상속받고있는데, 각 클래스를 확인해보면 AbstractCollection의 toString()메소드를 상속받아 사용하고 있는 것을 볼 수 있습니다.
```java
public String toString() {
        Iterator<E> it = iterator();
        if (! it.hasNext())
            return "[]";

        StringBuilder sb = new StringBuilder();
        sb.append('[');
        for (;;) {
            E e = it.next();
            sb.append(e == this ? "(this Collection)" : e);
            if (! it.hasNext())
                return sb.append(']').toString();
            sb.append(',').append(' ');
        }
    }
``` 
두 toString() 메소드는 이렇게 생겼는데 알고보니 map하고 set 출력하면 보이는 형태더라구요..
```java
map = {A=1, B=2, C=3}
set = [aa, bb, java.lang.Object@13969fbe]
```
이런 형태로 출력됩니다.

2.
음,,,우선 이 문장이 조금 어색한 부분이 있지 않나 라고 생각이 들긴합니다. `재정의(override)는 하위 클래스에서 상위 클래스의 메소드를 재정의` 하는 것이기 때문에, 이 문장에서 `재정의를 하는 주체가 상위 추상 클래스가 아닌 하위 클래스`라 생각했습니다. 그래서 저는 조금 다르게 이해했습니다.
`하위 클래스들이 공유해야 할 문자열 표현이 있는 추상 클래스라면 toString을 재정의해줘야 한다. 예컨데 대다수의 컬렉션 구현체는 추상 컬렉션 클래스들의 toString 메서드를 상속해 쓴다` 의 문장에서 `toString을 재정의해줘야한다` 라는 관점에서 생각해보았습니다.. 
앞의 문장 중, `열거타입은 이미 완벽한 toString을 제공하니 따로 재정의하지 않아도 된다` 라는 문장을 생각해보면, 1번 질문에서 보여드린 상위 추상 클래스의 toString()메소드가 이미 완벽하게 필드들을 설명해주고 있어 구체 클래스에서 이를 재정의하지 않고 상속받아 사용했다고 생각합니다. 따라서 저는 `상위 추상 클래스의 toString만으로는 표현이 되지 않는 문자열 표현 정도로 이해했습니다.`
이 답변이 맞는 답변일지는 모르겠네요,,저도 이 문장이 조금 이해하기가 힘들었습니다. 다른생각이있으시면 다시 코멘트 남겨주세요!!
