### ISSUE TITLE
[item 13] 생성자에서 재정의될 수 있는 메소드 사용 금지

### ISSUE THREAD

**Issue by NuhGnod** [2023-java-study/book-study#42]
p.84에서 2번째 문단 중 `만약 clone이 하위 클래스에서 재정의한 메서드를 호출하면, 하위 클래스는 복제 과정에서 자신의 상태를 교정할 기회를 잃는다.` 라는 문장에서
1. `하위 클래스에서 재정의한 메서드를 호출` 이 부분을 코드로 함께 설명해주시면 좋을 것 같습니다. 
clone()메소드는 파라미터로 하위 클래스의 인스턴스를 전달받지 않고 있는데, 어떻게 하위 클래스의 메서드를 호출하는지 궁금합니다.

3. `복제 과정에서 자신의 상태를 교정` 부분에 대한 좀더 구체적인 예시와 함께 설명해주시면 좋을 것 같습니다.
저는 우선 바로 뒷 문장의 put메서드는 final, private으로 해야한다는 글을 보고, 만약 put메서드는 원본의 데이터를 put해야 올바르겠지만, 사용자가 항상 null값을 put하는 메서드로 재정의해놓았다면 `원본과 복제본의 상태가 달라지는` 경우가 발생하게 될 것 입니다. 그래서 저는 이와 같은 케이스를 생각하며 해당 문장이 결국 데이터가 달라진다 정도로만 이해가 되어, `자신의 상태를 교정` 이 부분이 와닿지 않네요

**Comment by gmelon** [comment]
먼저 1번의 경우, 적절한 예시인지는 모르겠지만 아래와 같이 Parent 클래스와, 이를 상속받은 Child 클래스가 있다고 했을 때
```java
public class Parent {

    public void method() {
        printMessage();
    }

    public void printMessage() {
        System.out.println("Parent");
    }

}
```
```java
public class Child extends Parent {

    @Override
    public void method() {
        super.method();
    }

    @Override
    public void printMessage() {
        System.out.println("Child");
    }

    public static void main(String[] args) {
        Parent instance = new Child();
        instance.method();
    }

}
```
Child 클래스의 main 메서드 실행 결과는 `Child` 입니다. 즉, 현재 메서드가 호출되는 위치(클래스)와 관계없이 런타임에 어떤 인스턴스가 들어왔는가가 어떤 클래스의 메서드를 실행할지 결정하게 됩니다. 아마 다이나믹 디스패처가 이 역할을 수행할 것으로 생각됩니다.

따라서 질문 주신 내용 중 상위 클래스의 clone()이 하위 클래스의 인스턴스를 인자로 받지 않아도 현재 가지고 있는 `인스턴스` 자체는 하위 클래스의 것이기 때문에 `하위 클래스가 재정의한` 메서드가 실행될 수 있다고 이해하면 될 것 같습니다.

다음으로 2번은 저도 비슷하게 이해했었습니다. 우선 저는 `상태 교정`이 필드의 값을 정확하고, 깊게 복사하는 것을 의미한다고 생각했습니다. 따라서 말씀하신것처럼 하위 클래스에서 재정의한 메서드가 현재 (상위) 클래스에서 의도한바와 다르게 동작한다면 (이를테면 null을 넣거나 값을 두번 넣거나 등등) 현재 클래스에서 의도한대로 값을 정확하게 복사할 수 없을테니 clone에서 메서드를 호출할것이라면 현재 클래스에서만 사용가능하고 하위에선 재정의되지 못하게 final이나 private로 선언하라는 의미로 이해했습니다.
