### ISSUE TITLE
[item 14] 정렬된 컬렉션에서의 동치성 비교

### ISSUE THREAD

**Issue by NuhGnod** [2023-java-study/book-study#43]
p.90에서 `놀랍게도 정렬된 컬렉션 동치성을 비교할 equals 대신 compareTo를 사용하기 때문이다.`
에서 동치성이란 결국 같다는 것 인데 왜 `equals`나 `==`대신 굳이 compareTo를 사용하는 이유가 궁금합니다.

**Comment by ssstopeun** [comment]
해당 문장 아래의 예시를 코드로 작성해보았습니다.
```java
public class compareToLastRule {
    public static void main(String[] args) {
        BigDecimal bd1  = new BigDecimal("1.0");
        BigDecimal bd2 = new BigDecimal("1.00");


        HashSet<BigDecimal> hset = new HashSet<>();
        TreeSet<BigDecimal> tset = new TreeSet<>();

        hset.add(bd1);
        hset.add(bd2);
        System.out.println("hset cnt is " + hset.size());

        tset.add(bd1);
        tset.add(bd2);
        System.out.println("tset cnt is " + tset.size());
    }
}
```
이렇게 실행을 하였을 때 결과는 다음과 같이 나옵니다.
![image](https://github.com/2023-java-study/book-study/assets/68415975/6057595b-2457-4e00-9986-e839100b935b)

HashSet의 경우 equals() 를 사용해 중복값만 제거한 후 추가하고 treeset은 순서를 보장하기 위해 compareTo()를 사용하여 원소들을 추가하게 됩니다.

BigDecimal의 경우 equals로 비교하게 되면 소수점모두가 일치해야 true가 나오고 compareTo의 경우 소수점끝이 0인 부분은 제거하고 비교를 합니다. 따라서 hashSet과 treeSet의 결과가 다르게 나오게 됩니다. 

이렇게 값의 결과가 다르게 나오는 경우도 있고 정렬을 해야하는 컬렉션의 경우는 단순히 true/false가 결과로 나오는 equals가 아닌 대소관계까지 비교해 -1/0/1 로 나오는 compareTo가 정렬에 유리하기에 사용하는 것 같습니다.
