### ISSUE TITLE
[Item 15] 상속 클래스의 접근 제어자

### ISSUE THREAD

**Issue by gmelon** [2023-java-study/book-study#47]
package-private 인 클래스를 상속받은 클래스는 무조건 package-private 보다 좁거나 같은 권한만 가질 수 있나요?

public 클래스의 protected 메서드는 API가 된다고 했는데, package-private 클래스의 protected 메서드는 package-private 클래스를 상속받은 새로운 클래스가 public이 될 수 있다면 protected 메서드가 다시 API가 될 수 있을 것 같아서 이 점이 궁금했습니다.

**Comment by NuhGnod** [comment]
우선 p.98에서
protected 는 `package-private의 접근 범위를 포함하며, 이 멤버를 선언한 클래스의 하위 클래스에서도 접근할 수 있다.` 고 되어있습니다. 그리고 책에서는 `public클래스의 protected 멤버는 공개 API다` 라고 되어있는데 이를 우선 확인해보았을때 공개API가 아닌것 같다는 생각을 했습니다. 그 이유는 공개 API는 public과 같은 접근제한를 가져, 어디서든 접근 가능하다 라는 의미로 알고있습니다. 그래서 예제 코드를 짤 때, 이 public클래스를 상속받지 않은 class에서 접근해보았습니다.
디렉토리 구조는 directory(item15) - item15, directory(item15test) - main의 구조로 서로 다른 패키지에 위치해있습니다.

```java
package item15;

public class item15 {
    public int x=1;
    private int y=2;
    int d=3;
    protected int e=4;
    public static void main(String[] args) {
        PackPrivate pp = new PackPrivate(1);
        pp.getX();
        PackPrivateChild ppc = new PackPrivateChild(11);
        ppc.print();
        ppc.print2();
    }
    protected  void star(){
        System.out.println("star");
    }

    public void circle() {
        System.out.println("circle");
    }
}
```
![image](https://github.com/2023-java-study/book-study/assets/37896242/51e29bb6-3eb5-4400-982c-edffb850c0cf)
i.star() 의 에러를 보면 `star()메소드는 protected 접근 제한이다 라고 표시해주며, public으로 선언하라` 라고 알려주고 있습니다.
이는 우선 protected 접근제한자의 정의를 보면 다른 패키지에서 접근 했으니, 불가능할 것 이라고 봅니다. 하지만 책에서 말한대로 공개 API라면 가능해야한 것이 아닌가 하는 의문이 있습니다.

다음에는 상속받은 main클래스에서 사용해보았습니다.
```java
package item15test;


import item15.PackPrivateChild;
import item15.item15;

public class main extends item15{
    public static void main(String[] args) {
//        PackPrivate pp = new PackPrivate(2);

        PackPrivateChild ppc = new PackPrivateChild(12);
        chilchild cc = new chilchild(123);
        cc.printProtect();
    }
    public void method(){
        main i = (main) new item15();
        i.star();
    }

}

```
16line에서와 같이 item5인스터를 생성한뒤 main타입으로 다운캐스팅한 뒤 접근하니 가능합니다.
이 부분도 protected의 정의 처럼 상속받은 클래스에서 사용하고 있으니 당연히 가능한 상황인 것 같습니다.

여기까지 확인해보고 제가 생각한 `public클래스에서의 protected메소드가 공개API다` 는 상속받은 클래스가 다른 패키지에 존재하더라도 상위 클래스의 protected 멤버에 충분히 접근 가능하기 때문에 공개 API라고 보는 것이 아닌가 하는 생각입니다.

---

다시 본 질문으로 되돌아가면, 결론적으로 말씀해주신 상황은 가능하게 됩니다. 우선 예시 코드를 보여드릴게요.
우선 item15패키지의 package-private(default) 클래스인 PackPrivate입니다.
```java
package item15;

class PackPrivate {
    int x;
    public PackPrivate(int x) {
        this.x = x;
    }
    protected void printProtect() {
        System.out.println("PP print2 protected method");
    }
    public void print() {
        System.out.println("public method");
    }
}
```
그리고 같은 item15패키지에 있고, 이 클래스를 상속받고있는 public클래스인 PackPrivateChild 클래스입니다.
```java
package item15;

public class PackPrivateChild extends PackPrivate{
    public PackPrivateChild(int x) {
        super(x);
    }
    public void method(){
//        PackPrivateChild packPrivate = (PackPrivateChild) new PackPrivate(1);
        PackPrivate packPrivate1 = new PackPrivate(22);
        packPrivate1.printProtect();
//        packPrivate.printProtect();
    }
}
```
그리고 API가 될지 확인 해볼 item15test라는 다른 패키지에 존재하는 main클래스입니다.
```java
package item15test;


import item15.PackPrivateChild;
import item15.item15;

public class main{
    public static void main(String[] args) {
//        PackPrivate pp = new PackPrivate(2);
        PackPrivateChild packPrivateChild = new PackPrivateChild(2);
        packPrivateChild.method();
    }
//    public void method(){
//        main i = (main) new item15();
//        i.star();
//    }
}
```
테스트 해보게 되면 PackPrivateChild@method() -> PackPrivate@printProtect() -> 실행.
