### ISSUE TITLE
[Item 15] public 가변 필드를 갖는 클래스의 쓰레드 불안전

### ISSUE THREAD

**Issue by gmelon** [2023-java-study/book-study#48]
p.99에서 `필드가 수정될 때 (락 획득 같은) 다른 작업을 할 수 없게 되므로 public 가변 필드를 갖는 클래스는 일반적으로 스레드 안전하지 않다` 라는 문장이 잘 이해가 되지 않아서 어떻게 이해하셨는지 궁금합니다.

**Comment by NuhGnod** [comment]
제 생각에는 바로 앞 문장에서 `그 필돠와 관련된 모든 것은 불변식을 보장할 수 없게 된다는 뜻이다.` 라는 것을 보게되면, `락 획득`의 작업이 public필드와 관련이 있다면, 즉 public필드의 값(상태)에 따라 `락 획득`의 여부가 결정되는 경우를 말하는 것이 아닐까 생각합니다.
좀 더 생각해보면 `동시성 문제는 write작업일 때에 보통 문제가 발생하고 read시에는 문제가 괜찮다는 점`을 생각해보면,
A클라이언트가 어떤 객체의 public필드를 read한뒤에 write하려고 하는 상황입니다.
이 때, read하고 write하려는 그 순간에 다른 B 클라이언트가 먼저 write작업을 하게 된다면 Lock을 빼앗겨 A클라이언트가 정상적인 작업(또는 Lock획득)을 할 수 없게 될 것입니다. 이런 경우가 존재하므로 스레드 안전하지 않다. 라는 표현을 쓴거지 않나 싶습니다. 
( [이 글](https://hyojabal.tistory.com/3)에서 ReadWriteLock에 해당 되는 내용을 보면 도움이 될 것 같습니다.)
이는 동시성 쪽을 좀 더 공부해봐야 확실해 질 것 같네요.
