### ISSUE TITLE
[item 19] remove메소드의 @impleSpec

### ISSUE THREAD

**Issue by NuhGnod** [2023-java-study/book-study#55]
p.122 ~ p.123에 있는 java.util.AbstractCollection의 remove메소드의 주석을 보여주고 있는데,
제가 이 remove메소드 주석을 확인해봤는데  `Implementation Requirements`부분이 없기도하고 책이랑 주석내용도 조금 다른것 같은데 책에 있는 주석은 어디서 볼수 있는지 궁금합니다.

우선 저는 java11 쓰고 있고 제가 본 내용은 다음과 같습니다.
![image](https://github.com/2023-java-study/book-study/assets/37896242/f5e46f67-44a7-41c0-80b2-7306a018c53f)

**Comment by gmelon** [comment]
좌측에 문단모양 아이콘을 클릭해서 docs를 Reader Mode로 인코딩하면 볼 수 있습니다!

`@implSpec` 요 부분이 `Implementation Requirements` 로 변환되네요

<img width="733" alt="image" src="https://github.com/2023-java-study/book-study/assets/33623106/e87bf296-0853-4362-a067-471f66a8b9cb">
