### ISSUE TITLE
[item 19] removeRange메서드가 없을 때 clear메서드의 성능

### ISSUE THREAD

**Issue by NuhGnod** [2023-java-study/book-study#57]
p.124에서 `removeRange메서드가 없다면 하위 클래스에서 clear메서드를 호출하면 (제거할 원소 수의) 제곱에 비례해 성능이 느려지거나`라고 되어있는데,
이 문장이 이해가 되질 않네요.

우선 ArrayList, LinkedList 등 클래스를 보면 clear메소드는 removeRange를 사용하지 않고 for문으로 clear메서드를 구현해놓았습니다.
AbstractList의 clear메서드를 그대로 사용하는 list클래스가 있나 싶고,,
만약 있더라도 `제거할 원소 수의 제곱에 비례해 성능이 느려짐` 이 부분이 궁금합니다.

결국 removeRange또한 Iterator의 remove를 사용하여 1개씩 지우고 있는 걸텐데, 결국 이또한 `제거할 원소 수 만큼` 반복자가 돌며 remove를 수행하므로 동일한 시간이 걸리지 않나? 싶습니다.

**Comment by gmelon** [comment]
우선 조금 다른 이야기긴한데 p.124 API docs 부분에서 `주의 : ListIterator.remove가 선형 시간이 걸리면 이 구현의 성능은 제곱에 비례한다` 는 부분은 만약 해당 메서드에서 호출하는 `ListIterator` 인터페이스 구현체의 `remove()` 구현 방식이 `O(N)` 이면 성능이 제곱에 비례한다 는 이야기를 한 것 같습니다.

다음으로 질문해주신 내용에 대한 이야기로, p.124 API docs 다음 문단에서 이야기한 `단지 하위 클래스에서 부분리스트의 clear 메서드를 고성능으로 만들기 쉽게 하기 위해서` 라는 문장을 봤을 때 XxxList 보단 해당 List 구현체의 SubList에서 호출하는 clear를 이야기한게 아닌가 싶습니다. (물론 XxxList.clear()에서도 removeRange() 를 호출할 수도 있겠지만 이는 단순히 하위클래스 구현에 따라 즉, 구현 방식 상 removeRange()를 사용하도록 선택되는지 여부에 따라 달라지는게 아닐까 아닐까? 생각했습니다)

위 가정이 맞다는 전제하에 ArrayList와 ArrayList.SubList를 예로 들면, ArrayList.SubList.removeRange() 는 아래와 같이 재정의되어 있습니다.
```java
protected void removeRange(int fromIndex, int toIndex) {
    checkForComodification();
    root.removeRange(offset + fromIndex, offset + toIndex);
    updateSizeAndModCount(fromIndex - toIndex);
}
```

그리고, ArrayList.SubList 는 별도로 `clear()` 을 재정의하고 있지 않기에 부모 클래스인 (`private static class SubList<E> extends AbstractList<E> implements RandomAccess { ...`) `AbstractList.clear()` 을 호출하게 됩니다. `AbstractList.clear()` 는 내부적으로 removeRange()를 호출하므로 결국 `ArrayList.SubList` 에서 재정의한 `removeRange()` 가 호출되고 이는 책에서 말한 하위 클래스에서 재정의할 수 있도록 protected 메서드를 제공하는 방식에 해당한다고 볼 수 있을 것 같습니다.

질문 내용과 정확히 매칭되진 않아서 읽어보시고 좀 더 얘기 나누면 좋을 것 같습니다.

**Comment by NuhGnod** [comment]
ArrayList에 SubList라는 private static 클래스가 있는줄 몰랐네요..!
뭔가 쓸 일이 많을 것 같네요
