### ISSUE TITLE
[Item 18] 메서드 시그니처

### ISSUE THREAD

**Issue by gmelon** [2023-java-study/book-study#61]
자바 문법 관련 질문인데, p.117에서 언급하는 `메서드 시그니처는 같고 반환 타입은 다르다` 의 경우 컴파일러는 단순히 메서드가 중복된 것으로 판단하여 오류를 내는 걸까요??

**Comment by NuhGnod** [comment]
저도 그냥 당연히 안되는 거니깐 컴파일러가 잡아준다고 생각했습니다.
실제로도 그냥 에러경고를 내주기도하고 컴파일에러도 발생합니다.

그래서 컴파일러가 어떻게 메소드를 해석하여 컴파일하는지 알면 좋을 것 같아서 관련 내용을 찾아보려고 했는데 자료가 딱히 찾기 어렵네요..좀 더 찾아보고 좋은 내용이 있으면 다시 답변 드리겠습니다!
혹시 이와 관련된 내용을 알고 계시면 코멘트 달아주세요.!
