### ISSUE TITLE
[Item 18] 상속 대신 컴포지션을 사용할때의 getAccount

### ISSUE THREAD

**Issue by ssstopeun** [2023-java-study/book-study#65]
p.115에서 상속으로 코드를 구현하고 `s.addAll(List.of("틱","탁탁","펑펑"));` 을 실행했을 때 getAccount 메서드를 호출하면 6이 반환했다고 나옵니다. 그리고 뒤에 해결법으로 상속 대신 컴포지션을 사용한 코드로 해당 코드를 실행해보니 getAccount가 3이 잘 반환됐습니다.

컴포지션으로 구현했을 때 getAccount가 증가하는 과정이 잘 그려지지가 않습니다...ㅜ

**Comment by NuhGnod** [comment]
기존 상속 방식에서는 `InstrumentedHashSet` 이 HashSet의 하위 클래스 입니다. 
그래서 `InstrumentedHashSet set = new InstrumentedHashSet();`처럼 인스턴스를 생성한 경우 이 `set.메소드()`를 하게되면 호출되는 메소드는 `재정의한 메소드` 이게 됩니다. 그리고 책에서 말한 것 처럼 HashSet이 내부적으로 addAll() 메소드가 add()메소드를 이용하고 있어 재정의한 addAll()메소드가 문제를 일으키게 된거죠.

컴포지션 방식을 사용하게 되면, 내부 필드로 Set을 두고, Set<E>인터페이스의 구현체인 ForwardingSet클래스를 상속받고 있습니다. 이제는 `InstrumentedSet<String> set = new InstrumentedSet(new HashSet());` 와 같이 인스턴스를 생성하게 됩니다.
이때는 `set.A()` 를 했을떄 호출되는 메소드의 순서는  `재정의한 InstrumentedSet의 A()` -> `ForwardingSet의 A()` -> `인스턴스 생성시 넘겨받은 Set구현체 A()` 입니다.
그래서 최종적으로 실행되는 메소드는 Set구현체의 메소드이기 때문에 기존 방식처럼 addCount가 쓸데없이 중복되어 증가되지 않습니다.

---
실제 호출 순서는 아래처럼 됩니다.
![image](https://github.com/2023-java-study/book-study/assets/37896242/edbbc90d-c4ac-4af2-9d24-c1dbccd3bd77)
14번라인에 브레이크포인트를 걸고 확인해보면 다음으로 호출되는 메소드의 클래스는 `InstrumentedSet`클래스입니다.
![image](https://github.com/2023-java-study/book-study/assets/37896242/987298c8-5929-4210-b15b-f80a4f61f2ef)
우선 여기서 기존 방식처럼 addCount을 갯수만큼 증가시키고 `super.addAll(c)`로 부모 클래스(ForwardingSet)의 메소드를 호출합니다. 다음 호출되는 메소드의 클래스는 `ForwardingSet`입니다.
![image](https://github.com/2023-java-study/book-study/assets/37896242/12603b98-7dce-4bb4-a609-a90f312c6bc9)
현재 set은 HashSet이므로 다음에는` HashSet의  addAll()메소드`가 호출됩니다. HashSet의 addAll()은 `AbstractCollection의 메소드`를 상속받아 사용중 입니다.
![image](https://github.com/2023-java-study/book-study/assets/37896242/4e35c630-f83b-4892-9fa0-8e97bdd71e53)
352 line을 보면 내부적으로 add()메소드를 사용중임을 볼 수 있는데 컴포지션 방식으로 구현하였기에 이제는 `재정의한 InstrumentedSet의 add()메소드가 아닌 HashSet의 add()메소드`가 호출됩니다.
![image](https://github.com/2023-java-study/book-study/assets/37896242/9397201e-d67c-41b3-ae55-8c7788200995)

결과적으로 addCount는 재정의한 addAll()메소드에서 증가된 것이 끝이게 됩니다.
