### ISSUE TITLE
[Item 24] private 정적 멤버 클래스의 쓰임

### ISSUE THREAD

**Issue by gmelon** [2023-java-study/book-study#82]
p.148에 private 정적 멤버 클래스는 `흔히 바깥 클래스가 표현하는 객체의 한 부분을 나타낼 때 쓴다`고 되어있고, 예시로 Map.Entry 를 들었는데 이게 LinkedList.Node와 비슷한 느낌일까요??

해당 문장이 잘 이해되지 않아서 어떻게 이해하셨는지 궁금합니다.

**Comment by NuhGnod** [comment]
저는 WeakHashMap 클래스가 좀 더 이해하는데에 도움이 될 것 같습니다.
이 클래스에서 private static 클래스로 Entry클래스라 선언해놨습니다.
![image](https://github.com/2023-java-study/book-study/assets/37896242/3e09b329-5e68-4051-a6f0-13019fb719a8)
실제로 이 클래스에서  key-value의 값들은  Entry클래스를 사용합니다.
![image](https://github.com/2023-java-study/book-study/assets/37896242/4567a718-7a73-496f-a3a4-21a86196a1fd)
질문주신 문장의 다음,다음,다음 줄을 보면 `엔트리의 메서드들은 맵을 직접 사용하지는 않는다.`라고 되어있습니다.

위 Entry클래스에서 실제로도 `getKey(), getValue()` 메소드를 보면, WeakHashMap의 table에 접근하지 않고 Entry 클래스의 내부 필드인 value에 접근하여 반환하고 있습니다. p.147의 마지막에서 말한 것처럼 `멤버클래스에서 바깥 인스턴스에 접근할 일이 없다면 무조건 static을 붙여서 정적 멤버 클래스로 만들자`에도 부합하는 형태입니다.

추가로 private 접근 제한자로 지정한 것은, public으로 지정한다면 외부에서 해당 map의 내부 필드에 접근가능 해져 앞선 item들에서 계속 언급되었던 `불변`이 해쳐지게 되므로 private으로 제한한것 같습니다.
