### ISSUE TITLE
[item 26] 로 타입 사용의 두번째 예외

### ISSUE THREAD

**Issue by NuhGnod** [2023-java-study/book-study#87]
p.159에 로 타입 사용의 두번째 예외로 `instanceOf` 를 예시로 두고있습니다.

사실 이 문단이 전체적으로 이해가 가지 않네요.

1. `런타임에는 제네릭 타입 정보가 지워지므로 instanceOf 연산자는 비한정적 와일드카드 타입 이외의 매개변수화 타입에는 적용할 수 없다.` 의 의미.
2.  `로 타입이든 비한정적 와일드카드 타입이든 instanceOf는 완전히 똑같이 동작한다.` 어째서 이렇게 동작하는건가?
3. `코드26-7`은 무엇을 설명하려 하는건가?

좀 많긴한데 위 질문에 대해 설명해주실수 있을까요?

**Comment by ssstopeun** [comment]
제네릭의 타입소거를 찾아봤습니다. 제네릭은 원소 타입을 컴파일 시에만 검사하고 런타입때는 해당 타입정보를 알 수 없다고 합니다.

컴파일 때만 타입에 대한 제약을 두고 런타임에는 타입에 대한 정보가 없습니다. Set<String> 도 Set<Integer> 도 런타임때는 같은 Set으로 보이고 타입매개변수에 대한 정보는 알 수 없습니다.

instanceof 는 타입을 확인하는 것으로 `str instanceof String` 식으로 사용할 수 있습니다.

---
1. 에서 말하신 거는 위에 내용과 마찬가지로 Set<String> 이나 Set<Integer> 런타임때는 매개변수 정보가 없이 Set인지 아닌지만 확인해주기 때문에 적용할 수 없다고 한 것 같습니다. 

2. `o instanceof Set` 이나 `o instanceof Set<?>` 이나 o가 Set인지 확인해주는 것이기 때문에 똑같이 동작한다 인것 같습니다. 로타입 대신 비한정적와일드카드를 쓰라는 이유가 타입 불변식을 훼손할 수 있어서인데 instanceof 는 타입정보가 소거되니까 똑같이 작동하는구나 라고 생각했습니다.

3.

```java
public class InstanceOfTest {

    public static void main(String[] args) {
        Person person = new Person("지은",24);
        Animal animal = new Animal("Tom",5);

        Set<Person> setPerson = new HashSet<>();
        Set<Animal> setAnimal = new HashSet<>();
        Set set = new HashSet<>();

        setPerson.add(person);
        setAnimal.add(animal);

        checkPersonSet(setPerson);
        checkPersonSet(setAnimal);
    }


    private static void checkPersonSet(Set set) {
        if(set instanceof Set){
            Set<?> s = (Set<?>) set;
            if(set.iterator().next() instanceof Person){
                System.out.println("person 입니다.");
            }else{
                System.out.println("animal 입니다.");
            }
        }
//        if(set instanceof Set<Person>){
//
//        }
    }
}

```
이런 코드를 작성해 보았습니다. instanceof는 제네릭을 확인할때면 매개타입변수정보는 지워지므로 Set인지 아닌지 List인지 아닌지만 확인합니다. 
매개타입변수를 확인하려면 다음과 같이 set에 원소를 직접 꺼낸 후에 확인하는 방식을 사용해야 한다고 해요..
