### ISSUE TITLE
[Item 26] unckecked call 경고 메시지

### ISSUE THREAD

**Issue by gmelon** [2023-java-study/book-study#89]
p.155 에서 `실수로 Stamp 대신 Coin을 넣어도 아무 오류 없이 컴파일&실행 되지만 컴파일러가 unckecked call을 보여줄 것이다` 라고 합니다. 여기서 `unckecked call` 이라는 오류 메시지의 정확한 의미가 궁금합니다.

단순히 제네릭 타입을 로 타입으로 사용했을 때 띄워주는 경고인지, 다른 곳에서도 발생 가능한 경고인지 궁금하고 후자라면 그 예시가 궁금합니다.

**Comment by ssstopeun** [comment]
unchecked call이 아이템 27에서 나옴 비검사 경고 중에 하나입니다. 아이템 27에 나오는 비검사 경고 중 비검사 메서드 호출 경고가 unchecked call 에 해당합니다. 

비검사 메서드 호출 경고 : 제네릭 메서드 호출에서 발생하는 경고로 컴파일러가 해당 메서드 호출의 타입 안전성이 보장이 안될때 발생

비검사 메서드 호출 경고라는 것 자체가 컴파일러가 해당 메서드 호출의 타입 안전성이 보장안될 때 인데 이 경우가 로타입을 사용했을 때이기 때문에 해당 경우 밖에 없는 것 같습니다. p. 155에서의 예시와 같이 Collection stamps 에서 어떤 타입을 넣어도 되지만 stamps에 타입안전성이 보장이 안될때! 이 경우가 로타입을 사용했을 때! 인것같아요.

**Comment by gmelon** [comment]
https://www.baeldung.com/java-warning-unchecked-cast
