### ISSUE TITLE
[Item 26] 제네릭 하위 타입

### ISSUE THREAD

**Issue by gmelon** [2023-java-study/book-study#90]
`List<String>` 이 `List<Object>`의 하위타입이 되지 않도록 제네릭을 설계한 이유가 뭘까요?

제네릭 공부할 때부터 들었던 의문인데 String은 Object 의 하위 타입이므로 List<Object> 가 List<String>을 받아도 문제될 것이 없어보이는데 제네릭은 이걸 막고 있잖아요? 이렇게 설계된 이유가 분명 있을텐데 그게 뭘지 궁금합니다!

**Comment by gmelon** [comment]
Item 28에서 알려주네요 머쓱

**Comment by ssstopeun** [comment]
네! 저도 살짝 이해가 안된채로 넘어갔는데 28에서 아하..! 했어요!!!!
