### ISSUE TITLE
[Item 27] 27-1 예제 코드 unckecked 경고

### ISSUE THREAD

**Issue by gmelon** [2023-java-study/book-study#93]
p.163의 27-1 코드에서 `a.getClass()` 를 통해 a의 타입은 T[] 과 동일한 T[] 배열을 반환해주므로 안전한 형변환인 것은 이해했습니다. 그런데 Arrays.copyOf의 기본 반환 타입이 뭐길래 형변환을 해줘야되나요..? 라고 생각하고 코드를 돌려보니? Object[] 입니다.

그래서 질문은 **왜 Arrays.copyOf의 반환 타입이 Object[] 인가?** 입니다.

Arrays.copyOf는 이렇게 생겼는데,

```java
public static <T,U> T[] copyOf(U[] original, int newLength, Class<? extends T[]> newType) {
    @SuppressWarnings("unchecked")
    T[] copy = ((Object)newType == (Object)Object[].class)
        ? (T[]) new Object[newLength]
        : (T[]) Array.newInstance(newType.getComponentType(), newLength);
    System.arraycopy(original, 0, copy, 0,
                     Math.min(original.length, newLength));
    return copy;
}
```

처음에는 어? T[] 를 반환해주는데? 그럼 `a의타입[]` 을 반환해주는거 아냐? 라고 생각했습니다. 근데 아니었고 Object[] 였죠?

그래서 생각해보니 우선 Arrays.copyOf에서의 T[] 와 예제 코드에서의 T[]는 서로 전혀 별개의 T 겠더라구요. **그리고 애초에 넘겨줄 때 타입 매개변수 T를 넘겨주었기 때문에 Arrays.copyOf 입장에서는 해당 타입이 뭔지 알아낼 방법이 없었을거구요.** 그 반대 예시로 이렇게 String[]을 받으면 반환 타입이 제대로 String이 나오게 됩니다. (Arrays.copyOf에서 newType 인자로 받은 T가 임의의 T가 아닌 String인 것을 copyOf가 알고 있기 때문에 반환 값 T[] 을 String[]으로 설정 가능)

```java
public static <T> void method(String[] arr) {
    String[] strings = Arrays.copyOf(arr, arr.length, arr.getClass());
}
```

그냥 질문을 적다보니 이것저것 생각나서 주절주절 써보았는데 혹시 비슷한 궁금증이 들었던 분이 계셨다면 같이 얘기해보면 좋을 것 같아요!

**Comment by NuhGnod** [comment]
음 이번 item 들 공부하면서 공부해봐야 할게 많더라구요..
혼자 확인해보면서 의문이 들었던 것이기도하고, 질문 주신거 다시 해보면서 생겼던 궁금점인데,
`(T[]) new Object[newLength]` 같은 형태는 T[] 타입으로 Object가 다운 캐스팅 되는건데, 이러한 형태의 다운캐스팅 에러가 발생할텐데 어떻게 통과되나 였습니다. 물론 `copyOf`에서 (T[]) new Object[newLength] 가 실행될때는 T가 Object이긴 할 것 같은데, 그러면 왜 ` 다시  T[]로 형변환 하고 있나?`하는 의문이 생겼습니다.

그리고 마지막에 `그래서 생각해보니~~`부분이 어떤것을 설명해주신 건지 수요일날 만나서 얘기 해주시면 좋을것 같습니다!

추가로, 궁금한 부분은
```java
private static  Object Object() {
        Object integer = (Object) new Integer(1);
        return integer;
    }
```
처럼 사용하면 integer.getClass()는 Integer라고 나오더라구요. 이 부분이 좀 궁금했습니다. 

먼저, 위 코드를 작성해보게 된 이유  Arrays.copyOf 메소드 `Array.newInstance` 떄문입니다. 이 메소드는  Arrays.copyOf에서 사용됩니다. 그런데 `Array.newInstance`는 Object를 반환하고, 다시 `Arrays.copyOf`에서 
```java
T[] copy = ((Object)newType == (Object)Object[].class)
            ? (T[]) new Object[newLength]
            : (T[]) Array.newInstance(newType.getComponentType(), newLength);
```
형태로 (T[]) 다운 캐스팅을 하는데 아무런 에러가 없이 잘 작동하길래 확인해보았습니다. 

또한, `Array.newInstance` 에서는
```java
public static Object newInstance(Class<?> componentType, int length)
        throws NegativeArraySizeException {
        return newArray(componentType, length);
    }
``` 
`newArray` 메소드를 사용하여 반환합니다. 이 메소드는
```java
 @HotSpotIntrinsicCandidate
    private static native Object newArray(Class<?> componentType, int length)
        throws NegativeArraySizeException;
```
Object반환하는데 어떻게 된 일인가? 하고 있었는데, 

`Arrays.newInstance`메소드의 주석을 읽다가, `Creates a new array with the specified component type and length. Invoking this method is equivalent to creating an array as follows:
       int[] x = {length};
       Array.newInstance(componentType, x);` 라는 주석을 보고 생각난게 
`Obejct로 반환하지만 뭔가 타입이 Object인건 아닌건가??` 하는 생각이 들게되어 위 예시 메소드를 만들어서 확인해보았습니다.!

---

이 상태?를 이해하기 위해서 어떤 내용을 찾아보면 좋을지 조언해주시면 감사하겠습니다!!

**Comment by gmelon** [comment]
우선 다운캐스팅에 관련해서

아래와 같이 코드를 작성하면 (경고가 발생하긴 하지만) 컴파일은 문제 없이 됩니다.
```java
Object myClass = new MyClass();
Object integer = Integer.valueOf(10);

MyClass casting1 = (MyClass) myClass; // 가능
MyClass casting2 = (MyClass) integer; // 불가능
```

물론 실행 시키면 마지막 행에서 ClassCastException 이 발생하게 됩니다.

따라서 저는 다운 캐스팅 자체는 컴파일 레벨에서는 문제가 되지 않고 이를 사용하는 개발자가 직접 안전하게 캐스팅이 가능한지 판단 후 사용해야한다는 개념으로 이해했었습니다.

말씀해주신 예시의 경우 Arrays.copyOf() 메서드가 `Class<? extends T[]> newType` 와 같이 T[] 하위의 (T[]에 대입 가능한) 타입을 `newType` 으로 받고 이를 `Array.newInstance` 를 거쳐 `newArray`에 전달해주고 전달된 타입을 사용해 해당 타입의 배열을 반환해줄 것을 **명확하게 인지하고 있기 때문에** 절대 실패하지 않는 안전한 다운 캐스팅을 할 수 있었다고 생각합니다.
