### ISSUE TITLE
[item 29] 힙오염

### ISSUE THREAD

**Issue by ssstopeun** [2023-java-study/book-study#99]
p. 173 에서 `배열의 런타임 타입이 컴파일타임 타입과 달라 힙오염을 일으킨다.` 고 되있는데 이 힙오염이라는게 뭔지 잘 모르겠습니다..!

**Comment by gmelon** [comment]
<img width="741" alt="image" src="https://github.com/2023-java-study/book-study/assets/33623106/9365a7bc-3ed6-47c3-8a7a-b2bc3463c983">

**Comment by NuhGnod** [comment]
https://velog.io/@nuh__d/item-29-%EC%9D%B4%EC%99%95%EC%9D%B4%EB%A9%B4-%EC%A0%9C%EB%84%A4%EB%A6%AD-%ED%83%80%EC%9E%85%EC%9C%BC%EB%A1%9C-%EB%A7%8C%EB%93%A4%EB%9D%BC#generic-%EA%B8%B0%EB%B0%98-stack-1

해당 글에서 힙오염에 대해 말하며 책에서 말한 힙 오염으로 인해 발생될 만한 피해에 대해 예시를 들어보았습니다.~
